import type { KnowledgeRecord } from './types'

const updatedAt = '2026-05-13'

export const knowledgeRecords: KnowledgeRecord[] = [
  {
    id: 'food-rice-cooked',
    type: 'food_nutrition',
    title: '熟米饭',
    aliases: ['米饭', '白米饭', '蒸米饭'],
    summary: '常见主食，主要提供碳水。动态计划补餐时可作为适量主食来源。',
    tags: ['主食', '碳水', '补餐'],
    facts: { servingSize: '100g 熟重', calories: 116, protein: 2.6, carbs: 25.9, fat: 0.3 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-oats',
    type: 'food_nutrition',
    title: '燕麦片',
    aliases: ['燕麦', '即食燕麦'],
    summary: '适合早餐或加餐，饱腹感较好，注意搭配蛋白质食物。',
    tags: ['早餐', '主食', '高纤维'],
    facts: { servingSize: '40g 干重', calories: 150, protein: 5.1, carbs: 26, fat: 3 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-egg',
    type: 'food_nutrition',
    title: '鸡蛋',
    aliases: ['水煮蛋', '全蛋'],
    summary: '高性价比蛋白质来源，适合早餐和低负担加餐。',
    tags: ['蛋白质', '早餐', '加餐'],
    facts: { servingSize: '1个约50g', calories: 70, protein: 6.3, carbs: 0.4, fat: 5 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-chicken-breast',
    type: 'food_nutrition',
    title: '鸡胸肉',
    aliases: ['鸡胸', '去皮鸡胸肉'],
    summary: '低脂高蛋白，适合需要补蛋白或控制脂肪的餐次。',
    tags: ['蛋白质', '低脂', '健身'],
    facts: { servingSize: '100g 熟重', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-tofu',
    type: 'food_nutrition',
    title: '北豆腐',
    aliases: ['豆腐', '老豆腐'],
    summary: '植物蛋白来源，适合清淡晚餐和补蛋白。',
    tags: ['蛋白质', '植物蛋白', '清淡'],
    facts: { servingSize: '100g', calories: 82, protein: 8.1, carbs: 3.4, fat: 4.2 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-greek-yogurt',
    type: 'food_nutrition',
    title: '无糖希腊酸奶',
    aliases: ['希腊酸奶', '无糖酸奶'],
    summary: '适合下午加餐，优先选无糖款，搭配水果时注意总糖量。',
    tags: ['蛋白质', '加餐', '低脂'],
    facts: { servingSize: '100g', calories: 73, protein: 9.9, carbs: 3.9, fat: 1.9 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-apple',
    type: 'food_nutrition',
    title: '苹果',
    aliases: ['苹果', '水果'],
    summary: '低热量水果，适合作为轻加餐，但不能替代正餐蛋白质。',
    tags: ['水果', '加餐', '低热量'],
    facts: { servingSize: '1个中等约180g', calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-banana',
    type: 'food_nutrition',
    title: '香蕉',
    aliases: ['香蕉'],
    summary: '便携主食型水果，适合运动前后或需要轻补碳水时使用。',
    tags: ['水果', '碳水', '运动'],
    facts: { servingSize: '1根中等约120g', calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-broccoli',
    type: 'food_nutrition',
    title: '西兰花',
    aliases: ['西蓝花', '西兰花'],
    summary: '低热量蔬菜，适合晚餐增加体积和纤维。',
    tags: ['蔬菜', '低热量', '高纤维'],
    facts: { servingSize: '100g', calories: 35, protein: 2.4, carbs: 7.2, fat: 0.4 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'food-salmon',
    type: 'food_nutrition',
    title: '三文鱼',
    aliases: ['鲑鱼', '三文鱼'],
    summary: '富含蛋白质和脂肪，营养密度高，但热量比白肉鱼更高。',
    tags: ['蛋白质', '高脂', '鱼类'],
    facts: { servingSize: '100g 熟重', calories: 206, protein: 22, carbs: 0, fat: 12 },
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'guideline-plan-gap',
    type: 'guideline',
    title: '当日计划偏差处理',
    aliases: ['计划偏差', '少吃了怎么办', '吃超了怎么办'],
    summary: '当天实际摄入明显低于计划时，优先补 300-500 kcal 的蛋白质和适量主食；明显超出时，晚餐减少油脂和精制主食，不删除记录，不制造焦虑。',
    tags: ['动态计划', '主动提醒', '补餐'],
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'guideline-protein',
    type: 'guideline',
    title: '蛋白质优先级',
    aliases: ['蛋白质', '高蛋白', '补蛋白'],
    summary: '在热量不足或运动后，优先考虑鸡蛋、鸡胸肉、豆腐、无糖酸奶等蛋白质来源，再补充适量主食。',
    tags: ['蛋白质', '补餐', '运动'],
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'guideline-late-dinner',
    type: 'guideline',
    title: '晚餐清淡原则',
    aliases: ['晚餐', '清淡晚餐', '吃超了'],
    summary: '当天摄入偏高时，晚餐建议以蔬菜、低脂蛋白和少油烹饪为主，避免把某一餐当作惩罚。',
    tags: ['晚餐', '减餐', '低脂'],
    source: 'local_seed',
    updatedAt,
  },
  {
    id: 'guideline-health-safety',
    type: 'guideline',
    title: '健康安全边界',
    aliases: ['健康建议', '医生', '疾病', '极端热量'],
    summary: '涉及疾病、药物、孕期、进食障碍风险或极端热量缺口时，只给保守建议，并提醒遵循医生或营养师意见。',
    tags: ['安全', '医疗边界', '保守建议'],
    source: 'local_seed',
    updatedAt,
  },
]
